### ISSUE TITLE
Format exceptions add useful information

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-tools#14]
It would be nice if Exceptions like for example `FormatsRefClipMismatchError` would also display the formats of both clips in the `reason` by default. This makes it much easier to see which clip needs adjusting.

**Comment by Setsugennoao** [comment]
Would be resolved by implementing https://github.com/Irrational-Encoding-Wizardry/vs-tools/pull/45#discussion_r1088083622 .
