### ISSUE TITLE
Core proxy

### ISSUE THREAD

**Issue by YomikoR** [Irrational-Encoding-Wizardry/vs-tools#5]
foo.py
```python
from vstools import vs
import vapoursynth
resizer = vs.core.resize.Bicubic

def get_resizer():
    print('VS core:', vapoursynth.core)
    print('vstools core:', vs.core)
    return resizer

```

Untitled.vpy
```python
from foo import * 
clip = vs.core.std.BlankClip() 
clip = get_resizer()(clip)
 clip.set_output()
```

`vsedit Untitled.vpy` with F6 script checking (where VS core is acquired from the newly created script, and pointers are printed to stdout):
```
VS core: <vapoursynth._CoreProxy object at 0x7f0cf0188bb0>
vstools core: <vstools.utils.vs_proxy.VSCoreProxy object at 0x7f0ceaa61120>
Current core: 0x55f2b65b1f60
Current script: 0x55f2b65cd130
VS core: <vapoursynth._CoreProxy object at 0x7f0cf0188bb0>
vstools core: <vstools.utils.vs_proxy.VSCoreProxy object at 0x7f0ceaa61120>
Current core: 0x55f2b5be6ca0
Current script: 0x7f0cec007060
```

**Comment by Setsugennoao** [comment]
This is wrong usage. You are holding a reference to the Bicubic plugin and the core. core.proxied was made for this reason

**Comment by YomikoR** [comment]
I see. I was expecting a runtime error even without the proxied property.
BTW the culprit of dehalo_alpha crashing vsedit can be found [here](https://github.com/Irrational-Encoding-Wizardry/vsmask/blob/master/vsmask/util.py#L121). Things have to be watertight...

**Comment by Setsugennoao** [comment]
Thanks, will do a PR for updating vsmask soon.

**Comment by YomikoR** [comment]
I have one more question. Since it's safe to write `core = vs.core` in python modules, is it really necessary to wrap up the core instead of the following:
```python
class proxy_utils:
    @staticmethod
    def get_vs_core(**args):
        return vs.core
```
