### ISSUE TITLE
cannot install the very latest from git master, and release is "old"

### ISSUE THREAD

**Issue by hydra3333** [Irrational-Encoding-Wizardry/vs-tools#68]
Hello !

I see requirements.txt says 
rich>=12.6.0

And in the docs folder it says
rich==13.0.0

I'm not quire sure how to interpret it, is 13.0.0 for the documentation or something ?

Cheers

**Comment by hydra3333** [comment]
no need to answer this.

Using portable python 3.10 with setuptools, build and whatnot installed,
cannot build a wheel due to cannot import sequence from collections (3.0->3.10 issue).
Reverted to 3.9 and other issues present.

Latest release is "old" ... cannot install successfully from git (not portable git available to me), fails to install from a downloaded/extracted master .zip.

If I can't easily get the latest release installed into portable python 3.10, then unfortunately I can't use it ... which I really wanted to.

**Comment by Setsugennoao** [comment]
Docs have a pinned version because all the sphinx stuff is broken.

**Comment by Setsugennoao** [comment]
You should refer to tags rather than releases.
https://github.com/Irrational-Encoding-Wizardry/vs-tools/releases/tag/v2.0.5

To avoid future confusion, i deleted the release, since it was useless.

**Comment by hydra3333** [comment]
Cool !

Thank you.  I though my eyes were going when the release was no longer there.

Anyway, a vstools useful version installs fine from pip so I'm pleased as punch.
