### ISSUE TITLE
`FileType.parse` AssertionError on .log files

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-tools#71]
It can't find a `mime` for `.log` files, and so runs into an AssertionError.

**Comment by Setsugennoao** [comment]
Will be accepting PRs for adding stuff [here](https://github.com/Irrational-Encoding-Wizardry/vs-tools/blob/master/vstools/utils/__file_headers.json#L64)

**Comment by LightArrowsEXE** [comment]
You got any useful resources for figuring out the signatures, offsets, and all the other information?

**Comment by Setsugennoao** [comment]
Just open with hex editor in vscode, other stuff you also get from the file itself.
for plain text files, you don't need/have a signature.
But for log files that have a header etc you'll need to put it in
