### ISSUE TITLE
Suggestion: Additional Keyframes and Timecodes methods

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-tools#87]
It would be nice if we could get additional methods to obtain Keyframes and Timecodes objects.

## `.from_list`

The first suggestion would be for Keyframes: `.from_list`.
This would simply call `__init__` and pass the iterator.
The purpose of this is more so just to have a convenience function for people looking for it who aren't aware you can just pass a list directly to the class.

## `.from_wobbly`

The next one is a convenience method for wobbly usage and to speed up parsing, for both Keyframes and Timecodes.
This would go together with eventually(?) wobbly/wibbly updates in [vsdeinterlace](https://github.com/Irrational-Encoding-Wizardry/vs-deinterlace).
This should simply read the `.wob` file and construct the relevant object (from which the user can then write it to a file).

**Comment by Setsugennoao** [comment]
Wobbly parsing is out-of-scope and from_list would LITERALLY just call the constructor
