### ISSUE TITLE
Inconsistent method names

### ISSUE THREAD

**Issue by LightArrowsEXE** [Irrational-Encoding-Wizardry/vs-tools#88]
A handful of method names are inconsistent throughout this package (and other iew packages),
and I cannot really determine any logic behind some of them.

This is the one I thought of right now, but there are more.

![image](https://github.com/Irrational-Encoding-Wizardry/vs-tools/assets/42927908/d8ee0485-b413-4f76-8ca5-4af1a0e544ec)
![image](https://github.com/Irrational-Encoding-Wizardry/vs-tools/assets/42927908/5318c403-c96c-448e-84f7-b71793826b9e)

If I remember or find more, I will add them in a comment (and reopen if necessary).
If any of the listed ones do have some logic behind them, simply mark those specific instances as wontfix.

**Comment by Setsugennoao** [comment]
Explained in vc
